### PR TITLE
futureOnly option and current option can be mixed

### PR DESCRIPTION
**Pull request by HurSungYun**
For now, futureOnly option does not mixed with current option.

I think if there are both futureOnly option and current option, the start time of calendar should be current time. 

Therefore, I changed a bit for enhnacement.

Plus, I add Persian, Latvian, Lithuanian language which in #176 #179 and #180.

### CODE REVIEW

**Comment by HurSungYun** [comment]
Due to failure, I'm gonna check the code again.

**Comment by HurSungYun** [comment]
I found that master branch has same problem. Please make it correct.

**Comment by mugifly** [comment]
I'm sorry. I'll checking CI.

**Comment by mugifly** [comment]
Hi, @HurSungYun 

I fixed the version of jQuery of this plugin on the master branch.
To support for jQuery v3, it seems some fixes are required.

Could you merge the your master branch from the my latest master branch?

Thanks.

**Comment by HurSungYun** [comment]
I merged the master branch and it works well.

Thank you for fixing it quickly.

**Comment by mugifly** [comment]
@HurSungYun 
Sure :)
Thank you for your commit!

**Comment by HurSungYun** [comment]
@mugifly you are welcome. :)

**Pull request merged**
