### PR TITLE
External locale

### PR DESCRIPTION
**Pull request by royzrj**
If the library is used in an environment that does not support UTF-8, some pre-configured locales do not work as intended. The external_locale object enables the library use without modifications.

### CODE REVIEW

**Comment by royzrj** [comment]
I understand this modification requires updating the Wiki, explaining it's use.
@mugifly if you feel this pull is ok feel free to contact me to update the Wiki

**Comment by mugifly** [comment]
Thank you for your commits :)

It seems nice opinion!
But I think the external_locale object should be given as child of the config object as follows.

```js
$(function(){
    $('#date').appendDtpicker({
        locale: 'foo',
        externalLocale: {
            foo: {
                days: [],
                months: [],
                sep: '...',
                format: '...'
            }
        }
    });
});
```
What do you think for my opinion?

----

By the way... the options page of wiki isn't update recently.
Because it is duplicated effort with updating the examples page (jquery.simple-dtpicker.html).
So, please update the examples page in the repository, for now.
I apologize for that confusion. And thank you.

**Comment by royzrj** [comment]
@muglify nice, will modify the code as of now

**Comment by mugifly** [comment]
Thanks :+1:

**Pull request merged**
